In [1]:
import pandas as pd

In [2]:
# Load table ../../data/games.csv with pandas
df = pd.read_csv('../../data/games.csv')

In [3]:
df.tail()

,real_name,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
27521,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']
27522,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']
27523,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']
27524,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']
27525,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']

In [4]:
# Clean the dataframe where rows with the column "name" are empty
df = df[df['name'].notna() & (df['name'] != '')]

In [5]:
df.tail()

,real_name,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
27508,escapeVektor,escapeVektor: Chapter 1,2011-09-29,0.000,0.680000,0.0,0.75,0.76,"['Nintendo 3DS', 'PlayStation Vita']",0.0,0.0,0.0,['//images.igdb.com/igdb/image/upload/t_thumb/...,['Nnooo'],"['Nnooo', 'Arc System Works']",Help Vektor escape the clutches of the evil CP...,['English'],"['Puzzle', 'Puzzle', 'Adventure', 'Arcade', 'A...","['online', 'friends', 'destroy', 'hunt', 'esca..."
27512,void tRrLM();++ //Void Terrarium++,void tRrLM(); //Void Terrarium,NaN,0.000,0.000000,0.0,0.74,0.71,"['Nintendo Switch', 'PlayStation 4']",0.0,0.0,0.0,[],['Nippon Ichi Software'],"['NIS America', 'Nippon Ichi Software']",NaN,[],['Roguelike'],['']
27513,while True: learn,while True: learn(),2018-03-28,0.732,0.000000,0.0,0.73,0.61,"['iOS', 'PC', 'macOS', 'Linux', 'Nintendo Swit...",3.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Luden.io'],['Nival Interactive'],while True: learn() is a puzzle/simulation gam...,[],"['Simulation', 'Educational', 'Indie', 'Puzzle...","['Singleplayer', 'Early Access', 'Education', ..."
27514,UberSoldier,UberSoldier II,2008-07-22,0.672,0.000000,0.0,0.57,0.53,['PC (Microsoft Windows)'],6.0,0.0,0.0,['//images.igdb.com/igdb/image/upload/t_thumb/...,['Burut Software'],"['cdv Software', 'Strategy First']",Hunt down the war criminals\n\nIt is April of ...,"['English', 'English', 'French', 'German', 'Ge...","['Action', 'Shooter', 'Strategy', 'Strategy', ...","['Singleplayer', 'FPS', 'Violent', 'War', 'Wor..."
27515,Wipeout,Wipeout Pulse,2008-02-12,0.000,0.676408,0.0,0.00,0.83,"['PlayStation 3', 'Android', 'DOS', 'Sega Satu...",0.0,0.0,0.0,['//images.igdb.com/igdb/image/upload/t_thumb/...,['Psygnosis'],"['Psygnosis', 'SCEA', 'SCEI', 'SCEE']",SCE Studios Liverpool brings the future back w...,"['Japanese', 'English']","['Racing', 'Future Racing']","['playstation network', 'digital distribution'..."

In [6]:
# Clean the dataframe where rows with the column "name" must not repeat
df = df.drop_duplicates(subset=['name'], keep='first')

In [7]:
df.tail()

,real_name,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
27323,The Wolf Among Us: Episode 2 - Smoke and Mirrors,The Wolf Among Us: Episode 2 - Smoke and Mirrors,NaN,0.000,0.000000,0.0,0.76,0.83,"['PC', 'PlayStation 3', 'Xbox 360', 'iOS (iPho...",0.0,0.0,0.0,[],['Telltale Games'],['Telltale Games'],NaN,[],['Point-and-Click'],['']
27334,Tiger Woods PGA Tour 2001,Tiger Woods PGA Tour 2001,2000-11-06,0.000,0.000000,0.0,0.74,0.00,"['PlayStation', 'PlayStation 2', 'PC']",0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Stormfront Studios'],"['EA Sports', 'Electronic Arts Victor', 'Elect...",Swing into action with the first-ever PS2 golf...,[],"['Sports', 'Golf Sim']","['Singleplayer', 'Multiplayer', '']"
27375,Treasure Stack,Treasure Stack,2019-03-01,0.000,0.000000,0.0,0.61,0.00,"['Nintendo Switch', 'Xbox One', 'PC']",0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['PixeLakes LLC'],['PixeLakes LLC'],Treasure Stack is now available for wish listi...,[],"['Action', 'Indie', 'Stacking Puzzle']","['Singleplayer', 'Steam Achievements', 'Multip..."
27472,Winter Stars,Winter Stars,2011-11-09,0.000,0.000000,0.0,0.46,0.65,"['PlayStation 3', 'Xbox 360']",0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['49Games'],['Deep Silver'],"Winter Stars, developed by 49 Games, entices g...",[],"['Sports', 'Sports']","['speed', 'winter', 'Everyone']"
27501,Zenge,Zenge,2016-04-12,0.682,0.600106,0.0,0.00,0.00,"['Linux', 'Windows Phone', 'Android', 'PC (Mic...",3.0,0.0,0.0,['//images.igdb.com/igdb/image/upload/t_thumb/...,['Hamster On Coke Games'],['Hamster On Coke Games'],"Zenge is a peculiar puzzle game, telling the s...","['English', 'Polish', 'Polish', 'Portuguese (P...","['Adventure', 'Casual', 'Indie', 'Puzzle', 'Pu...","['Singleplayer', 'Steam Achievements', 'steam-..."

In [8]:
# Save the new dataframe with name ../../data/games_2.csv
df.to_csv('../../data/games_2.csv', index=False)
print("Data cleaning complete. Saved to ../../data/games_2.csv")

Data cleaning complete. Saved to ../../data/games_2.csv