In [1]:
import pandas as pd

In [2]:
# Load table ../../data/games.csv with pandas
df = pd.read_csv('../../data/games.csv')

In [3]:
df.head()

,id,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
0,0,! That Bastard Is Trying To Steal Our Gold !,2014-05-11,0.0,0.0,0.0,0.0,0.34,"['PC', 'Linux']",5.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['WTFOMGames'],['WTFOMGames'],It's a fun puzzle game where you need to steal...,[],"['Action', 'Adventure', 'Casual', 'Indie', 'Pu...","['Singleplayer', 'steam-trading-cards', 'Parti..."
1,1,!nsane,2016-03-31,0.0,0.0,0.0,0.0,0.00,[],0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,[],[],"!nsane is a nod to the cult game ""Logical"" fro...",[],[],['']
2,2,"""Glow Ball"" - The billiard puzzle game",2014-02-16,0.0,0.0,0.0,0.0,0.13,"['PC', 'Linux']",4.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['WTFOMGames'],['WTFOMGames'],Physics based puzzle game type of billiards.\n...,[],"['Strategy', 'Sports', 'Casual', 'Indie', 'Puz...","['Singleplayer', 'Atmospheric', 'steam-trading..."
3,3,"""You have a choice. Make it.""",2014-07-23,0.0,0.0,0.0,0.0,0.25,['PC'],0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Venusaur'],['Venusaur'],NaN,[],['JRPG'],['']
4,4,#1 Crosswords,2021-02-12,0.0,0.0,0.0,0.0,0.00,['Nintendo Switch'],0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Eclipse Games'],['Eclipse Games'],Are you a fan of crosswords? Do you enjoy spen...,[],['Logic Puzzle'],['']

In [4]:
# Clean the dataframe where the column "id" is removed
df = df.drop(columns=['id'], errors='ignore')

In [6]:
df.tail()

,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
23715,NaN,NaN,0.000,0.0,0.0,0.00,0.00,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']
23716,NaN,NaN,0.000,0.0,0.0,0.00,0.00,[],0.0,0.0,0.0,[],[],[],NaN,[],[],['']
23717,ArcaniA: Fall of Setarrif,NaN,0.476,0.0,0.0,0.41,0.34,['PC'],1.0,0.0,0.0,[],['Spellbound'],['Nordic Games Publishing'],Face the last challenge - determine destiny!\n...,[],"['Action', 'RPG', 'Action RPG']","['Singleplayer', 'RPG', 'Fantasy', 'Gothic', '']"
23718,ArcaniA - The Complete Tale,NaN,0.000,0.0,0.0,0.42,0.48,"['Xbox 360', 'PlayStation 3', 'PlayStation 4']",0.0,0.0,0.0,[],['Spellbound'],['Nordic Games Publishing'],Decide the battle for the future of Argaan!\nT...,[],"['RPG', 'Action RPG']",['Teen']
23719,Are You Smarter Than a 5th Grader? (Capcom),2007-10-02,0.000,0.0,0.0,0.58,0.56,"['PC', 'Android', 'Nintendo 3DS', 'Nintendo DS']",5.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Massive Miniteam'],"['THQ Nordic', 'HandyGames']",How well do you remember the 5th grade? Was it...,[],"['Casual', 'Trivia']","['Singleplayer', 'Steam Achievements', 'Multip..."

In [8]:
# Clean the dataframe where rows with the column "name" are empty
df = df[df['name'].notna() & (df['name'] != '')]

In [9]:
df.tail()

,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
23672,Arcade Archives Atomic Robo-Kid,NaN,0.000,0.0,0.0,0.00,0.00,['Nintendo Switch'],0.0,0.0,0.0,[],[],"['HAMSTER', 'Co.']",'Atomic Robo-Kid' is a shoot'em up game releas...,[],[],"['Robots', 'battle', 'fight', 'shoot', 'dungeo..."
23686,Arcade Archives Mario Bros.,NaN,0.000,0.0,0.0,0.00,0.00,['Nintendo Switch'],0.0,0.0,0.0,[],[],"['HAMSTER', 'Co.']",Mario Bros. is an action game released by Nint...,[],[],"['work', 'mario', '']"
23717,ArcaniA: Fall of Setarrif,NaN,0.476,0.0,0.0,0.41,0.34,['PC'],1.0,0.0,0.0,[],['Spellbound'],['Nordic Games Publishing'],Face the last challenge - determine destiny!\n...,[],"['Action', 'RPG', 'Action RPG']","['Singleplayer', 'RPG', 'Fantasy', 'Gothic', '']"
23718,ArcaniA - The Complete Tale,NaN,0.000,0.0,0.0,0.42,0.48,"['Xbox 360', 'PlayStation 3', 'PlayStation 4']",0.0,0.0,0.0,[],['Spellbound'],['Nordic Games Publishing'],Decide the battle for the future of Argaan!\nT...,[],"['RPG', 'Action RPG']",['Teen']
23719,Are You Smarter Than a 5th Grader? (Capcom),2007-10-02,0.000,0.0,0.0,0.58,0.56,"['PC', 'Android', 'Nintendo 3DS', 'Nintendo DS']",5.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Massive Miniteam'],"['THQ Nordic', 'HandyGames']",How well do you remember the 5th grade? Was it...,[],"['Casual', 'Trivia']","['Singleplayer', 'Steam Achievements', 'Multip..."

In [10]:
# Clean the dataframe where rows with the column "name" must not repeat
df = df.drop_duplicates(subset=['name'], keep='first')

In [11]:
df.tail()

,name,release,rawg_rating,igdb_rating,hltb_rating,metacritic_rating,user_rating,platforms,main_story,main_extra,completionist,cover_url,developers,publishers,description,language_supports,genres,keywords
21920,Dragon Marked For Death,2019-01-29,0.578,0.0,0.0,0.69,0.69,"['PC', 'Nintendo Switch', 'PlayStation 4']",6.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Inti Creates'],"['Inti Creates', 'Nighthawk Interactive']",Dragon MFD is a 2D side-scrolling action RPG g...,[],"['Action', 'RPG', 'Action RPG']","['Singleplayer', 'Steam Achievements', 'Multip..."
21921,Dragon Nest,2011-09-28,0.708,0.0,0.0,0.00,0.72,['PC'],3.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Eyedentity Games'],"['Nexon', 'E-Frontier']",Dragon Nest follows the story of a band of adv...,[],"['Action', 'Adventure', 'RPG', 'Casual', 'Mass...","['Multiplayer', 'RPG', 'Co-op', 'Story Rich', ..."
21937,60 Seconds!,2015-05-26,0.712,0.0,0.0,0.63,0.66,"['Xbox One', 'Nintendo Switch', 'PlayStation 4...",3.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['Robot Gentleman'],['Robot Gentleman'],60 Seconds! is a dark comedy atomic adventure ...,[],"['Adventure', 'Strategy', 'Simulation', 'Casua...","['Singleplayer', 'Steam Achievements', 'Steam ..."
22031,AiRace Speed,2013-09-19,0.000,0.0,0.0,0.68,0.75,['Nintendo 3DS'],0.0,0.0,0.0,['https://www.gamespot.com/a/uploads/original/...,['QubicGames'],"['QubicGames', 'Flyhigh Works']","Take the challenge in AiRace Speed, the third ...",[],['Future Racing'],"['online', 'achievements', 'race', 'challenge'..."
22045,Aliens: Colonial Marines - Stasis Interrupted,NaN,0.000,0.0,0.0,0.00,0.54,"['PC', 'Xbox 360', 'PlayStation 3']",0.0,0.0,0.0,[],['Gearbox Software'],['Sega'],NaN,[],['FPS'],['']

In [17]:
# Load gamespot reviews
df_reviews = pd.read_csv("../../data/reviews.csv")
unique_games = [f"{game_name}" for game_name in df_reviews["game_name"].unique()]
unique_games.sort()

In [19]:
unique_games[::-1]

['xXx',
 'xFart',
 'while True: learn()',
 'while True: learn',
 'void tRrLM();++ //Void Terrarium++',
 'void tRrLM(); //Void Terrarium',
 'vib-ribbon',
 'uDraw Studio: Instant Artist',
 'uDraw Studio',
 'to a T',
 'theHunter: Call of the Wild',
 'the World According to Girl',
 'stikir',
 'somnus',
 'slither.io',
 'simian.interface++',
 'see/saw',
 'satryn deluxe',
 'sZone-Online',
 's.p.l.i.t',
 'rymdkapsel',
 'realMyst: Masterpiece Edition',
 'realMyst',
 'rain',
 'rFactor 2',
 'rFactor',
 'pureya',
 'osu!stream',
 'orbt xl',
 'oOo: Ascension',
 'non - The First Warp',
 'netWAR',
 'nan',
 "nail'd",
 'moon: Remix RPG Adventure',
 'moon',
 'missed messages.',
 'lilt line',
 'kuso',
 'klocki',
 'kill.switch',
 "it's always monday",
 'indiecalypse',
 'inbento',
 'inZOI',
 'inMomentum',
 'inFamous: Second Son',
 'inFamous: First Light',
 'inFamous: Festival of Blood',
 'inFamous Collection',
 'inFamous 2',
 'inFamous',
 'ilomilo',
 'illWill',
 'id Anthology',
 'iStunt 2 - Snowboard',
 'iRacing',
 "iPanzer '44",
 'iM1A2 Abrams',
 'iF/A-18E Carrier Strike Fighter',
 'iF-22 Persian Gulf v5.0',
 'iF-22',
 'iF-16',
 'iCarly 2: iJoin The Click',
 'iCarly',
 'iBomber Defense Pacific',
 'iBomber Defense',
 'iBlast Moki',
 'htoL#NiQ: The Firefly Diary',
 'how do you Do It?',
 'hocus.',
 'hocus 2',
 'hexceed',
 'gravilon',
 'forma.8',
 'flower',
 'flocks',
 'flOw (2006)',
 'flOw',
 'fault milestone one',
 'everlasting flowers',
 'escapeVektor: Chapter 1',
 'escapeVektor',
 'echoshift',
 'echochrome ii',
 'echochrome',
 'eFootball PES 2021',
 'eFootball PES 2020',
 'eFootball 2026',
 'eFootball 2025',
 'eFootball 2024',
 'eFootball 2023',
 'eFootball 2022',
 'drowning (Rapture)',
 'diep.io',
 'despelote',
 'de Blob 2',
 'de Blob',
 'continue?9876543210',
 'click to ten',
 'chick chick BOOM',
 'blurred weird night',
 'bit Dungeon II',
 'bayala - the game',
 'art of rally',
 'aerofly FS',
 'aMAZE 2',
 '[REDACTED]',
 '[REC] Desolation',
 'Zzed',
 'Zup! Zero',
 'Zup! 2',
 'Zumba Garden',
 'Zumba Fitness: Join the Party',
 'Zumba Fitness World Party',
 'Zumba Fitness Rush',
 'Zumba Fitness Core',
 'Zumba Burn it Up!',
 "Zuma's Revenge! (DSiWare)",
 "Zuma's Revenge!",
 'Zuma Deluxe',
 'Zuma (2005)',
 'Zuma',
 'Zula - Europe',
 'Zueirama',
 'Zubo',
 'Zotrix',
 'Zork: Grand Inquisitor',
 'Zork Nemesis',
 'Zork Grand Inquisitor',
 'Zootopia Crime Files: Hidden Object',
 'Zoop',
 'Zoombinis',
 'Zool Redimensioned',
 'Zoochosis',
 'ZooZooGo!',
 'ZooKeeper Simulator',
 'ZooCube',
 'Zoo Tycoon: Ultimate Animal Collection',
 'Zoo Tycoon: Complete Collection',
 'Zoo Tycoon DS',
 'Zoo Tycoon 2: Ultimate Collection',
 'Zoo Tycoon 2: Endangered Species',
 'Zoo Tycoon 2',
 'Zoo Tycoon (2001)',
 'Zoo Tycoon',
 'Zoo Simulator',
 'Zoo Resort 3D',
 'Zoo Keeper DX',
 'Zoo Keeper',
 'Zoo Hospital',
 'Zoo 2: Animal Park',
 'Zone of the Enders: The Fist of Mars',
 'Zone of the Enders: The 2nd Runner MARS',
 'Zone of the Enders: The 2nd Runner',
 'Zone of the Enders HD Collection',
 'Zone of the Enders',
 'Zone Raiders',
 'Zombotron',
 'Zombocalypse Now',
 'Zombocalypse',
 'Zombillie',
 'Zombii Attack',
 'Zombiewood',
 'Zombieville USA 3D',
 'Zombieville USA 2',
 'Zombies.',
 'Zombies ruined my day',
 'Zombies Monsters Robots',
 'Zombies Ate My Neighbors and Ghoul Patrol',
 'Zombieland: Double Tap - Road Trip',
 'Zombie Wranglers',
 'Zombie Vikings',
 'Zombie Tycoon',
 'Zombie Tsunami',
 'Zombie Shooter 2',
 'Zombie Shooter',
 'Zombie Rollerz: Pinball Heroes',
 'Zombie Revenge',
 'Zombie Pirates',
 'Zombie Pinball',
 'Zombie Party (2015)',
 'Zombie Party',
 'Zombie Panic! Source',
 'Zombie Panic in Wonderland',
 'Zombie Night Terror',
 'Zombie Infection',
 'Zombie Highway 2',
 'Zombie HQ',
 'Zombie Farm 2',
 'Zombie Driver: Immortal Edition',
 'Zombie Driver HD',
 'Zombie Driver',
 'Zombie Catchers',
 'Zombie Bowl-O-Rama',
 'Zombie Boom',
 'Zombie Army Trilogy',
 'Zombie Army 4: Dead War',
 'Zombie Apocalypse: Never Die Alone',
 'Zombie Apocalypse (2009)',
 'Zombie Apocalypse',
 'Zombidle: REMONSTERED',
 'ZombiU',
 'Zombi',
 'Zombeer',
 'Zoids: Legacy',
 'Zoids: Battle Legends',
 'Zoids Wild: Blast Unleashed',
 'Zoids Assault',
 'Zoey 101',
 'Zodiac DX',
 "Zoboomafoo: Leapin' Lemurs!",
 'Zniw Adventure',
 'Ziro',
 "Zill O'll",
 'Ziggurat 2',
 'Ziggurat',
 'Zigfrak',
 'ZhuZhu Pets: Featuring The Wild Bunch',
 'Zeus: Master of Olympus',
 'Zeroptian Invasion',
 'Zero Zero Zero Zero',
 'Zero Tolerance',
 'Zero Strain',
 'Zero Hour',
 'Zero Gunner 2-',
 'Zero Gear',
 'Zero Escape: Zero Time Dilemma',
 "Zero Escape: Virtue's Last Reward",
 'Zero Escape: The Nonary Games',
 'Zero Divide 2: The Secret Wish',
 'Zero City: Zombies Apocalypse',
 'Zenzizenzic',
 'Zenonia 4: Return of the Legend',
 'Zenonia 3: The Midgard Story',
 'Zenonia',
 'Zenohell',
 'Zenodyne R',
 'Zeno Clash: Ultimate Edition',
 'Zeno Clash II',
 'Zeno Clash',
 'Zenless Zone Zero',
 'Zenith: The Last City',
 'Zenith (2016)',
 'Zenith',
 'Zenge',
 'Zen Bound 2',
 'Zen Bound',
 'Zelda II: The Adventure of Link',
 'Zeit Squared',
 'Zazmo Arcade Pack',
 'Zax: The Alien Hunter',
 'Zathura',
 'Zatch Bell! Mamodo Fury',
 'Zatch Bell! Mamodo Battles',
 'Zapper',
 'Zanzarah: The Hidden Portal',
 'Zanki Zero: Last Beginning',
 'Zanac',
 'Zam BeeZee',
 'Zafehouse: Diaries',
 'Zack Zero',
 "Zack & Wiki: Quest for Barbaros' Treasure",
 'Zaccaria Pinball',
 'ZPC',
 'ZHP: Unlosing Ranger vs. Darkdeath Evilman',
 'ZHEROS',
 'ZERO Sievert',
 'ZERO PROTOCOL',
 'ZEPHON',
 'ZENONIA',
 'ZEN Pinball 3D',
 'ZEN Pinball 2: The Walking Dead',
 'ZEN Pinball 2: Star Wars Pinball',
 'ZEN Pinball 2: South Park: Super-Sweet Pinball',
 'ZEN Pinball 2: Portal Pinball',
 'ZEN Pinball 2: Ant-Man Pinball',
 'ZEN Pinball 2',
 'ZEN Pinball',
 'ZCREW',
 'ZAMB! Redux',
 'ZAAM',
 'Z.H.P. Unlosing Ranger vs Darkdeath Evilman',
 'Z-Warp',
 'Z-Run',
 'Z The Game',
 'Z',
 'Yuppie Psycho',
 'Yupitergrad',
 'Yu-Gi-Oh! Zexal: World Duel Carnival',
 'Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel',
 'Yu-Gi-Oh! World Championship Tournament 2004',
 'Yu-Gi-Oh! World Championship 2008',
 'Yu-Gi-Oh! World Championship 2007',
 'Yu-Gi-Oh! The Sacred Cards',
 'Yu-Gi-Oh! The Falsebound Kingdom',
 'Yu-Gi-Oh! The Eternal Duelist Soul',
 'Yu-Gi-Oh! The Duelists of the Roses',
 'Yu-Gi-Oh! The Dawn of Destiny',
 'Yu-Gi-Oh! Reshef of Destruction',
 'Yu-Gi-Oh! RUSH DUEL: Dawn of the Battle Royale!!',
 'Yu-Gi-Oh! Power of Chaos: Yugi the Destiny',
 'Yu-Gi-Oh! Online',
 'Yu-Gi-Oh! Nightmare Troubadour',
 'Yu-Gi-Oh! Millennium Duels',
 'Yu-Gi-Oh! Master Duel',
 'Yu-Gi-Oh! Legacy of the Duelist: Link Evolution',
 'Yu-Gi-Oh! Legacy of the Duelist',
 'Yu-Gi-Oh! GX: The Beginning of Destiny',
 'Yu-Gi-Oh! GX: Spirit Caller',
 'Yu-Gi-Oh! GX: Duel Academy',
 'Yu-Gi-Oh! GX Tag Force',
 'Yu-Gi-Oh! Forbidden Memories',
 'Yu-Gi-Oh! Early Days Collection',
 'Yu-Gi-Oh! Dungeon Dice Monsters',
 'Yu-Gi-Oh! Duel Monsters 6 Expert 2',
 'Yu-Gi-Oh! Duel Links',
 'Yu-Gi-Oh! Destiny Board Traveler',
 'Yu-Gi-Oh! Dark Duel Stories',
 'Yu-Gi-Oh! Capsule Monster Coliseum',
 'Yu-Gi-Oh! 7 Trials to Glory: World Championship Tournament 2005',
 "Yu-Gi-Oh! 5D's: Duel Transer",
 "Yu-Gi-Oh! 5D's World Championship 2011: Over the Nexus",
 "Yu-Gi-Oh! 5D's World Championship 2010: Reverse of Arcadia",
 "Yu-Gi-Oh! 5D's Tag Force 5",
 "Yu-Gi-Oh! 5D's Tag Force 4",
 "Yu-Gi-Oh! 5D's Stardust Accelerator: World Championship 2009",
 "Yu-Gi-Oh! 5D's Decade Duels Plus",
 "Yu-Gi-Oh! 5D's Decade Duels",
 'Yu Yu Hakusho: Dark Tournament',
 'Yu Yu Hakusho - Ghost Files: Tournament Tactics',
 'Yu Yu Hakusho - Ghost Files: Spirit Detective',
 'Ys: The Oath in Felghana',
 'Ys: The Ark of Napishtim',
 'Ys: Memories of Celceta',
 'Ys: Ancient Ys Vanished',
 'Ys X: Nordics',
 'Ys VIII: Lacrimosa of DANA',
 'Ys VI: The Ark of Napishtim',
 'Ys Seven',
 'Ys Origin',
 'Ys Memoire: The Oath in Felghana',
 'Ys IX: Monstrum Nox',
 'Ys I & II Chronicles',
 'Ys Chronicles II',
 'Ys Chronicles 1',
 'Youtubers Life: OMG Edition',
 'Youtubers Life 2',
 'Youtubers Life',
 'Yourself!Fitness',
 'Youropa',
 'Your Toy',
 'Your Shape: Fitness Evolved',
 'Your Shape Fitness Evolved 2012',
 'Your Shape Featuring Jenny McCarthy',
 'Your Only Move Is HUSTLE',
 'Your Doodles Are Bugged!',
 'Your Adventure',
 'Young Souls',
 'Young Justice: Legacy',
 "You've Got a Package",
 "You're in the Movies",
 'You Will Die Here Tonight',
 'You Suck at Parking',
 'You Must Build A Boat',
 'You Have to Win the Game',
 'You Have 10 Seconds',
 "You Don't Know Jack: Volume 4 - The Ride",
 "You Don't Know Jack: Volume 3",
 "You Don't Know Jack: Volume 2",
 "You Don't Know Jack: Sports",
 "You Don't Know Jack: Movies",
 "You Don't Know Jack: Mock 2",
 "You Don't Know Jack: 5th Dementia",
 "You Don't Know Jack 6: The Lost Gold",
 "You Don't Know Jack (2011)",
 "You Don't Know Jack (1999)",
 "You Don't Know Jack",
 'You Deserve',
 'You Are Not a Banana',
 'You Are Grounded',
 'You Are Empty',
 'Yosumin!',
 "Yoshi's Woolly World",
 "Yoshi's Story",
 "Yoshi's New Island",
 "Yoshi's Island: Super Mario Advance 3",
 "Yoshi's Island DS",
 "Yoshi's Crafted World",
 'Yoshi Touch & Go',
 'Yoshi Topsy-Turvy',
 'Yoshi (1991)',
 "Yorna: Monster Girl's Secret",
 "Yorbie - Episode One: Payback's a Bolt",
 'Yoot Tower',
 'Yoostar 2: In The Movies',
 'Yooka-Replaylee',
 'Yooka-Laylee and the Impossible Lair',
 'Yooka-Laylee',
 'Yono and the Celestial Elephants',
 'Yonder: The Cloud Catcher Chronicles',
 'Yomawari: The Long Night Collection',
 'Yomawari: Night Alone',
 'Yomawari: Midnight Shadows',
 "Yoku's Island Express",
 'Yohane the Parhelion - NUMAZU in the MIRAGE -',
 'Yogi Bear',
 'Yoga',
 'Yo-kai Watch: Geraporhythm',
 'Yo-kai Watch Jam: Yo-kai Academy Y - Waiwai Gakuen Seikatsu',
 'Yo-kai Watch Blasters: White Dog Squad',
 'Yo-kai Watch Blasters: Red Cat Corps',
 'Yo-kai Watch 4++',
 'Yo-kai Watch 3',
 'Yo-kai Watch 2: Psychic Specters',
 'Yo-kai Watch 2: Fleshy Souls',
 'Yo-kai Watch 2: Bony Spirits',
 'Yo-kai Watch 2',
 'Yo-kai Watch',
 'Yo-Ho Kablammo',
 'Yo Yo Fighter',
 'Yield! Fall of Rome',
 'Yie Ar Kung Fu',
 "Yggdra Union: We'll Never Fight Alone",
 'Yet Another Zombie Survivors',
 'Yet Another Zombie Defense HD',
 'Yet Another Zombie Defense',
 'Yesterday Origins',
 'Yesterday',
 'YesterMorrow',
 'Yes, Your Grace',
 'Yes, Master!',
 'Yeeps: Hide and Seek',
 'Year Walk',
 'Year Unknown',
 'Yasai Ninja',
 'Yars Rising',
 'Yaris',
 'Yard Sale Hidden Treasures: Sunnyville',
 "Yar's Revenge",
 "Yao Ming Basketball '04",
 'Yanya Caballista: City Skater',
 'Yakuza: Like a Dragon',
 'Yakuza: Dead Souls',
 'Yakuza Kiwami 2',
 'Yakuza Kiwami',
 'Yakuza 6: The Song of Life',
 'Yakuza 5 Remastered',
 'Yakuza 5',
 'Yakuza 4 Remastered',
 'Yakuza 4',
 'Yakuza 3 Remastered',
 'Yakuza 3',
 'Yakuza 2',
 "Yakuza 0: Director's Cut",
 'Yakuza 0',
 'Yakuza',
 'Yaiba: Ninja Gaiden Z',
 'Yahtzee Deluxe',
 'Yahoo! Solitaire',
 'Yahoo! Hearts',
 'Yager',
 'Yaga',
 'YUMENIKKI -DREAM DIARY-',
 'YRek Lost In Portals',
 'YO-KAI WATCH Wibble Wobble',
 'YIIK: A Postmodern RPG',
 'YIIK Nameless Psychosis',
 'YEAH! YOU WANT "THOSE GAMES," RIGHT? SO HERE YOU GO! NOW, LET\'S SEE YOU CLEAR THEM!',
 'YAIBA: NINJA GAIDEN Z',
 'Y2K: The Game',
 'Y. Village - The Visitors',
 'Xyanide',
 'Xuan-Yuan Sword: The Gate of Firmament',
 'Xuan-Yuan Sword VII',
 'Xuan-Yuan Sword 7',
 'Xtreme Sports',
 'Xtreme Air Racing',
 'Xsyon',
 'Xpand Rally Xtreme',
 'Xpand Rally',
 'Xotic',
 'Xiaolin Showdown',
 'Xevious 3D/G+',
 'Xevious',
 'Xeodrifter',
 'Xenus II: White Gold',
 'Xenosaga Episode III: Also sprach Zarathustra',
 'Xenosaga Episode II: Jenseits von Gut und Bose',
 'Xenosaga Episode I: Der Wille zur Macht',
 'Xenoraid',
 'Xenophage: Alien Bloodsport',
 'Xenonauts',
 'Xenon Valkyrie+',
 'Xenon Racer',
 'Xenogears',
 'Xenoblade Chronicles: Definitive Edition',
 'Xenoblade Chronicles X: Definitive Edition',
 'Xenoblade Chronicles X',
 'Xenoblade Chronicles 3D',
 'Xenoblade Chronicles 3: Expansion Pass Wave 4 - Future Redeemed',
 'Xenoblade Chronicles 3',
 'Xenoblade Chronicles 2: Torna ~ The Golden Country',
 'Xenoblade Chronicles 2: New Quests Pack 1',
 'Xenoblade Chronicles 2',
 'Xenoblade Chronicles',
 'XenoRaptor',
 'Xeno Crisis',
 'Xena: Warrior Princess - The Talisman of Fate',
 'Xena: Warrior Princess (1999)',
 'Xbox Series X',
 'Xbox One',
 'Xbox Live Arcade Unplugged Volume 1',
 'Xbox Live Arcade Compilation Disc',
 'Xbox Fitness',
 'Xatrom Command',
 'Xanadu Next',
 'XXX: State of the Union',
 'XS',
 'XING: The Land Beyond',
 'XIII Century: Death or Glory',
 'XIII (Remake)',
 'XIII',
 'XGRA: Extreme G Racing Association',
 'XGIII: Extreme G Racing',
 'XEL',
 'XDefiant',
 'XCar: Experimental Racing',
 'XCOM: Enemy Within',
 'XCOM: Enemy Unknown Plus',
 'XCOM: Enemy Unknown - Slingshot',
 'XCOM: Enemy Unknown - Second Wave',
 'XCOM: Enemy Unknown',
 'XCOM: Chimera Squad',
 'XCOM 2: War of the Chosen',
 'XCOM 2 Collection',
 'XCOM 2 - Alien Hunters',
 'XCOM 2',
 'X: Beyond the Frontier',
 'X4: Timelines',
 'X4: Foundations',
 'X3: Terran Conflict',
 'X3: Reunion',
 'X3: Albion Prelude',
 "X2: Wolverine's Revenge",
 'X2: The Threat',
 'X-Tension',
 'X-Squad',
 'X-Scape',
 'X-Plane 8',
 'X-Plane 11',
 'X-Plane',
 'X-Out: Resurfaced',
 'X-Morph: Defense',
 "X-Men: Wolverine's Rage",
 'X-Men: The Ravages of Apocalypse',
 'X-Men: The Official Game',
 'X-Men: The Arcade Game',
 'X-Men: Reign of Apocalypse',
 'X-Men: Next Dimension',
 'X-Men: Mutant Wars',
 'X-Men: Mutant Academy 2',
 'X-Men: Mutant Academy',
 'X-Men: Destiny',
 'X-Men: Children of the Atom',
 'X-Men vs. Street Fighter',
 'X-Men Origins: Wolverine',
 'X-Men Legends II: Rise of Apocalypse',
 'X-Men Legends',
 'X-Men 2: Battle',
 'X-MEN ORIGINS: WOLVERINE',
 'X-COM: UFO Defense',
 'X-COM: Terror From the Deep',
 'X-COM: Interceptor',
 'X-COM: First Alien Invasion',
 'X-COM: Enforcer',
 'X-COM: Apocalypse',
 'X-Blades',
 'X Rebirth',
 'Wylde Flowers',
 'Wuthering Waves',
 'Wurroom',
 'Wuppo',
 'Wunderling DX',
 'Wunderling',
 'Wumpus',
 'Wulverblade',
 'Wu-Tang: Shaolin Style',
 'Wrought Flesh',
 'Wrong Floor (2020)',
 'Wrong Floor',
 'Written in the Sky',
 'Written Legends: Nightmare at Sea',
 'Wrestling Spirit',
 'Wrestling Revolution HD',
 'Wrestling Revolution 3D',
 'Wrestling Empire',
 'WrestleQuest',
 'Wrench',
 'Wreckreation',
 'Wreckless: The Yakuza Missions',
 'Wrecking Crew',
 'Wreckfest',
 'Wrecked: Revenge Revisited',
 'Wreckateer',
 'Wrath: Aeon of Ruin',
 'Wrath Unleashed',
 'Wrap House Simulator',
 'Wraith: The Oblivion - Afterlife',
 'Wrack',
 'Woven',
 'Worse Than Death',
 'Worms: Open Warfare 2',
 'Worms: Open Warfare',
 'Worms: Battle Islands',
 'Worms: A Space Oddity',
 'Worms World Party Remastered',
 'Worms World Party',
 'Worms W.M.D',
 'Worms Ultimate Mayhem',
 'Worms Rumble',
 'Worms Revolution',
 'Worms Reloaded',
 'Worms Pinball',
 'Worms Forts: Under Siege',
 'Worms Crazy Golf',
 'Worms Collection',
 'Worms Clan Wars',
 'Worms Blast',
 'Worms Battlegrounds',
 'Worms Armageddon',
 'Worms 4: Mayhem',
 'Worms 3D',
 'Worms 2: Armageddon',
 'Worms 2',
 'Worms',
 'Worldwide Soccer Manager 2009',
 'Worldwide Soccer Manager 2008',
 'Worldwide Soccer Manager 2007',
 'Worldwide Soccer Manager 2005',
 'Worldwide Soccer',
 'Worlds of Magic',
 'Worlds of Aria',
 'Worldless',
 'WorldShift',
 "World's Scariest Police Chases",
 "World's End Club",
 'World to the West',
 'World of Warships: Legends',
 'World of Warships',
 'World of Warriors',
 'World of Warplanes',
 'World of Warcraft: Wrath of the Lich King Classic',
 'World of Warcraft: Wrath of the Lich King',
 'World of Warcraft: Warlords of Draenor',
 'World of Warcraft: The War Within',
 'World of Warcraft: The Burning Crusade',
 'World of Warcraft: Shadowlands',
 'World of Warcraft: Mists of Pandaria',
 'World of Warcraft: Legion',
 'World of Warcraft: Dragonflight',
 'World of Warcraft: Cataclysm',
 'World of Warcraft: Battle for Azeroth',
 'World of Warcraft Classic: Burning Crusade Classic',
 'World of Warcraft Classic',
 'World of Warcraft',
 'World of Van Helsing: Deathtrap',
 'World of Tanks: Xbox 360 Edition',
 'World of Tanks Blitz',
 'World of Tanks',
 'World of Outlaws: Sprint Cars 2002',
 'World of Outlaws: Sprint Cars',
 'World of Outlaws: Dirt Racing 24',
 'World of One',
 'World of Mixed Martial Arts 2',
 'World of Horror',
 'World of Guns: Gun Disassembly',
 'World of Goo 2',
 'World of Goo',
 'World of Final Fantasy Maxima',
 'World of Final Fantasy',
 'World of Demons',
 'World of Battles: Morningstar',
 'World of Battles',
 'World of Aden: Thunderscape',
 'World in Conflict: Soviet Assault',
 'World in Conflict: Complete Edition',
 'World in Conflict',
 'World War Z: Aftermath',
 'World War Z',
 'World War III: Black Gold',
 'World War II: Prisoner of War',
 'World War II: Panzer Claws',
 'World War II: Frontline Command',
 'World War II Online: Blitzkrieg',
 'World War II Combat: Road to Berlin',
 'World War II Combat: Iwo Jima',
 'World War Battle Heroes Field Armies Call of Prison Duty Simulator',
 'World Tour Soccer 2006',
 'World Tour Soccer 2005',
 'World Tour Soccer 2003',
 'World Tour Soccer 2002',
 'World Tour Soccer 06',
 'World Tour Soccer',
 'World Super Police',
 'World Sports Competition',
 'World Soccer Winning Eleven 9',
 'World Soccer Winning Eleven 8 International',
 'World Soccer Winning Eleven 7 International',
 'World Soccer Winning Eleven 6 International',
 'World Series of Poker: Tournament of Champions',
 'World Series of Poker: Full House Pro',
 "World Series of Poker Hold'em Legend",
 'World Series of Poker Deluxe Casino Pak',
 'World Series of Poker 2008: Battle for the Bracelets',
 'World Series of Poker',
 'World Series Baseball II',
 'World Series Baseball 2K3',
 'World Series Baseball 2K2',
 'World Series Baseball 2K1',
 'World Series Baseball',
 'World Racing 2',
 "World Poker Tour: Texas Hold 'Em",
 'World Poker Tour (2005)',
 'World Poker Tour',
 'World Poker Championship (2004)',
 'World Heroes Anthology',
 'World Heroes',
 'World Gone Sour',
 'World Enduro Rally',
 'World End Syndrome',
 'World Driver Championship',
 'World Destruction League: Thunder Tanks',
 'World Cup 98',
 'World Conqueror X',
 'World Class Baseball',
 'World Championship Pool 2004',
 'World Championship Poker: Featuring Howard Lederer - All In',
 'World Championship Poker: Deluxe Series',
 'World Championship Poker 2: Featuring Howard Lederer',
 'World Championship Paintball',
 'World Championship Boxing Manager',
 'Workshop Simulator',
 'Workers & Resources: Soviet Republic',
 'Wordmaster (2008)',
 'Wordle 4',
 'Wordle 3',
 'Wordle (2020)',
 'Wordament',
 'WordKing Poker',
 'WordJong',
 'Word Sudoku by POWGI',
 'Word Puzzle',
 'Word Nerd',
 'Word Mojo',
 'Word Heaven',
 'Word Ace',
 'Worbital',
 'Woolfe - The Red Hood Diaries',
 'Woody Woodpecker: Escape from Buzz Buzzard Park',
 'Woody Woodpecker Racing',
 'Woody Woodpecker',
 'Woody Two-Legs: Attack of the Zombie Pirates',
 'Woodle Tree Adventures Deluxe',
 'Woodle Tree Adventures',
 'Woodle Tree 2: Deluxe+',
 'Woodle Tree 2: Deluxe',
 'Wooden Ships & Iron Men',
 'Wooden Floor',
 'Woodcutter Simulator 2013',
 "Wonka's World of Candy",
 'Wonderland (2005)',
 'Wonderbook: Walking with Dinosaurs',
 'Wonderbook: Book of Spells',
 'Wonder World Amusement Park',
 'Wonder Project J2',
 "Wonder Boy: The Dragon's Trap",
 'Wonder Boy: Asha in Monster World',
 'Wonder Boy in Monster World',
 'Wonder Boy Returns Remix',
 'Wonder Boy Returns',
 "Wonder Boy III: The Dragon's Trap",
 'Wonder Boy Collection',
 'Wonder Blade',
 'Wolfstride',
 'Wolfenstein: Youngblood',
 'Wolfenstein: The Old Blood',
 'Wolfenstein: The New Order',
 'Wolfenstein: Cyberpilot',
 'Wolfenstein RPG',
 'Wolfenstein II: The New Colossus - The Diaries of Agent Silent Death',
 'Wolfenstein II: The New Colossus - The Amazing Deeds of Captain Wilkins',
 'Wolfenstein II: The New Colossus - The Adventures of Gunslinger Joe',
 'Wolfenstein II: The New Colossus',
 'Wolfenstein 3D',
 'Wolfenstein',
 'WolfQuest',

In [20]:
from thefuzz import fuzz

# Function to decide the equalness of two strings
def nameRatio(name1: str, name2: str) -> bool:
    return fuzz.ratio(name1, name2) / 100.0

nameRatio("RealMyst", "RealMyst 2")

0.89

In [22]:
from tqdm import tqdm

map_game_names = {}
for game in tqdm(df["name"], desc="Mapping game names"):
    # Find best match
    max_name_ratio = 0.0
    max_index = 0
    for index, game_name in enumerate(unique_games):
        current_name_ratio = nameRatio(game, game_name)
        if current_name_ratio > max_name_ratio:
            max_name_ratio = current_name_ratio
            max_index = index
    # Map result of query game names to name in unique games
    map_game_names[game] = unique_games[max_index]

Mapping game names: 100%|██████████| 20754/20754 [22:06<00:00, 15.64it/s]

In [23]:
map_game_names["Red Dead Redemption"]

'Red Dead Redemption'

In [24]:
# Create a new column "real_name" that holds the mapped game names
df["real_name"] = df["name"].map(map_game_names)

In [26]:
# Reorder columns to place "real_name" first
cols = df.columns.tolist()
cols.remove('real_name')
df = df[['real_name'] + cols]

In [27]:
# Save the new dataframe with name ../../data/games_2.csv
df.to_csv('../../data/games_2.csv', index=False)
print("Data cleaning complete. Saved to ../../data/games_2.csv")

Data cleaning complete. Saved to ../../data/games_2.csv